### ISSUE TITLE
Warn when above maximum water threshold

### ISSUE THREAD

**Issue by wired-brain** [wired-brain/wired-espresso#2]
## Problem

When a user pours in too much water, we don't validate whether the amount of water in the machine is above the threshold (causing overflows).

## Expected Results

Warn when water is above threshold.

## Actual Results

Machine overflows because user can accidentally go over threshold.

## Proposed Solution

In `Reservoir.ts`, in the `validate` method we should check the water level and throw an error if its above the maximum threshold. We will need to define a new error constant, `WATER_ABOVE_THRESHOLD_ERROR` with a code. Ensure test coverage is added so we don't regress.

**Comment by kamranayub** [comment]
Since it's OBVIOUS @wired-cupofjoe gave up on this, I can take it.

**Comment by wired-brain** [comment]
@wired-cupofjoe it looks like we have an open PR #17 for this change! 😄

**Comment by wired-brain** [comment]
@wired-cupofjoe it looks like we have an open PR #17 for this change! 😄
