### ISSUE TITLE
Remove workaround adding an extra degree to temperature control for LUCCA V3 hardware

### ISSUE THREAD

**Issue by wired-brain** [wired-brain/wired-espresso#3]
## Context

In the past, the thermostat hardware used in [LUCCA M58 V2](https://clivecoffee.com/products/lucca-m58-espresso-machine-by-quick-mill) espresso systems would incorrectly report the user's entered temperature. If the system was using an LUCCA V2 thermostat, we'd subtract a degree from the reported temperature. In our firmware, we are classifying all LUCCA thermostats this way.

Now as of LUCCA M58 V3, they fixed that bug and we need to remove the workaround. We need to distinguish between the two thermostat versions and only apply the workaround to V2 hardware and not V3.

## Proposed Solution

In `PID.ts` in the method `applyRequestedTemperature` we need to check `DeviceContext.version` for v3 under the `LUCCA_M58` switch statement and only apply the temperature modification to v2.

**Comment by kamranayub** [comment]
Is this available to work on?

**Comment by wired-brain** [comment]
@kamranayub All yours, please open a draft PR as soon as you can and let us know if you get stuck!

**Comment by kamranayub** [comment]
Hi @wired-brain I just opened a PR #9 to address this issue if you'd like to take a look. Thank you!
